export const SYMPTOM_QUESTIONS: Record<string, string> = {
  Abdominal_Bloating: "Are you experiencing abdominal bloating?",
  Abdominal_Pain: "Are you experiencing abdominal pain?",
  Abnormal_Menstruation: "Have you noticed abnormal menstruation?",
  Acidity: "Are you experiencing acidity or acid reflux?",
  Anal_Burning: "Do you feel a burning sensation around the anus?",
  Anal_Pain: "Are you experiencing anal pain?",
  Anorexia: "Have you lost your appetite severely?",
  Anxiety: "Are you feeling anxious?",
  Back_Pain: "Are you experiencing back pain?",
  Bladder_Insufficiency: "Are you having trouble controlling your bladder?",
  Bleeding_from_the_Navel: "Have you noticed bleeding from your navel?",
  Blisters: "Do you have blisters on your skin?",
  Blisters_on_the_lips: "Do you have blisters on your lips?",
  Bloating: "Are you experiencing bloating?",
  Blood_Clot: "Have you noticed any blood clots?",
  Bloody_Diarrhea: "Are you experiencing bloody diarrhea?",
  Bloody_Stool: "Have you noticed blood in your stool?",
  Blurred_Vision: "Are you experiencing blurred vision?",
  Body_Pain: "Are you experiencing pain throughout your body?",
  Bones_of_the_legs_curved_like_bow:
    "Have your leg bones become curved, like a bow?",
  Breast_Enlargement: "Have you noticed breast enlargement?",
  Brittle_Bones: "Do you have brittle bones that fracture easily?",
  Brittle_Gums: "Are your gums brittle?",
  Burning_Eyes: "Do your eyes feel like they're burning?",
  Burning_Sensation:
    "Are you experiencing a burning sensation anywhere on your body?",
  Burning_Urination: "Do you feel a burning sensation when urinating?",
  Chest_Pain: "Are you experiencing chest pain?",
  Chest_Pain_With_Pressure:
    "Are you experiencing chest pain along with pressure?",
  Clay_Colored_Stool: "Have you noticed clay-colored stool?",
  Cognitive_Decline:
    "Have you noticed a decline in your memory or thinking ability?",
  Cold: "Do you feel cold or have cold-like symptoms?",
  Color_Fading_Appearance:
    "Have you noticed your skin or features fading in color?",
  Coma: "Has the patient been in a coma?",
  Constipation: "Are you experiencing constipation?",
  Continuous_Sneezing: "Are you sneezing continuously?",
  Corneal_Damage: "Have you experienced any damage to your cornea?",
  Cough: "Do you have a cough?",
  Coughing_Blood: "Are you coughing up blood?",
  Coughing_With_Mucus: "Are you coughing with mucus?",
  Crippled: "Have you become severely disabled or unable to move normally?",
  Dark_Colored_Urine: "Have you noticed dark-colored urine?",
  Dark_Gums: "Have your gums darkened in color?",
  Dehydration: "Are you experiencing dehydration?",
  Deja_vu: "Have you been having episodes of déjà vu?",
  Diarrhea: "Are you experiencing diarrhea?",
  Difficulty_in_Defecation: "Do you have difficulty defecating?",
  Difficulty_Swallowing: "Do you have difficulty swallowing?",
  Dislike_of_food: "Have you developed an aversion to food?",
  Dizziness: "Are you feeling dizzy?",
  Double_vision: "Are you seeing double?",
  Dry_Skin: "Do you have dry skin?",
  Ear_Fluid_Drainage: "Is fluid draining from your ear?",
  Ear_Pain: "Are you experiencing ear pain?",
  Enlarged_Liver: "Has your liver become enlarged?",
  Excessive_Bleeding: "Are you experiencing excessive bleeding?",
  Excessive_Hunger: "Are you experiencing excessive hunger?",
  Excessive_Salivation: "Are you salivating excessively?",
  Eye_Discomfort: "Are you experiencing discomfort in your eyes?",
  Eye_Pain: "Are you experiencing eye pain?",
  Eye_Problems: "Are you experiencing any other eye problems?",
  Facial_Droop: "Have you noticed drooping on one side of your face?",
  Fainting: "Have you fainted recently?",
  Family_History: "Does your family have a history of this condition?",
  Fatigue: "Are you feeling fatigued?",
  Fear_of_the_Wind: "Do you have an unusual sensitivity or fear of wind?",
  Chills: "Are you experiencing chills?",
  Fever: "Do you have a fever?",
  Frequent_Urination: "Are you urinating more frequently than usual?",
  Genital_Pain: "Are you experiencing genital pain?",
  Gingivitis: "Do your gums bleed or look inflamed?",
  Gum_Abscess: "Do you have an abscess on your gums?",
  Gums_Swell: "Are your gums swollen?",
  Hard_Muscle: "Do your muscles feel unusually hard or stiff?",
  Head_Scratching: "Do you find yourself scratching your head frequently?",
  Headache: "Do you have a headache?",
  "Hearing Difficulty": "Are you having difficulty hearing?",
  Hearing_Difficulty: "Are you having difficulty hearing?",
  Hearing_Loss: "Have you experienced hearing loss?",
  Heartburn: "Are you experiencing heartburn?",
  Heaviness: "Do you feel a general sense of heaviness in your body?",
  High_Fever: "Do you have a high fever?",
  Hole_in_the_Gum: "Have you noticed a hole forming in your gum?",
  Inability_to_Focus: "Are you having trouble focusing or concentrating?",
  Inability_to_walk: "Are you unable to walk?",
  Indigestion: "Are you experiencing indigestion?",
  Insomnia: "Are you having trouble sleeping?",
  Itching: "Are you experiencing itching?",
  Bone_Stiffness: "Do your bones feel stiff?",
  Joint_Pain: "Are you experiencing joint pain?",
  Shared_Pain:
    "Are you experiencing pain that seems to radiate or be shared across areas?",
  Loose_Tooth: "Do you have a loose tooth?",
  Loss_of_Appetite: "Have you lost your appetite?",
  Loss_of_Balance: "Are you experiencing a loss of balance?",
  Loss_of_Consciousness: "Have you lost consciousness?",
  Loss_of_sense_of_smell_and_taste:
    "Have you lost your sense of smell or taste?",
  Memory_Loss: "Have you experienced memory loss?",
  Mental_Anxiety: "Are you experiencing mental anxiety?",
  Mood_Swings: "Are you experiencing mood swings?",
  Mucus_in_the_throat: "Do you have mucus in your throat?",
  Muscle_Pain: "Are you experiencing muscle pain?",
  Muscle_Weakness: "Are you experiencing muscle weakness?",
  Nasal_Inflammation: "Is your nose inflamed?",
  Nausea: "Are you feeling nauseous?",
  Neck_Pain: "Are you experiencing neck pain?",
  Neck_Swelling: "Is your neck swollen?",
  Numbness: "Are you experiencing numbness anywhere in your body?",
  Open_Wound: "Do you have an open wound?",
  Pain_Behind_Eyes: "Are you experiencing pain behind your eyes?",
  Pain_in_hands_and_feet: "Are you experiencing pain in your hands and feet?",
  Painful_Defecation: "Is defecation painful for you?",
  Pale_Spots_On_Skin: "Have you noticed pale spots on your skin?",
  Paralysed_Body: "Is any part of your body paralyzed?",
  Paralysis: "Are you experiencing paralysis?",
  Phlegm: "Do you have phlegm?",
  Poor_night_vision: "Has your night vision become poor?",
  Prickly_Heat_Rash: "Do you have a prickly heat rash?",
  Pulse_Rate_Decrease: "Has your pulse rate decreased?",
  Pus_Filled_Pimple: "Do you have pus-filled pimples?",
  Pus_from_the_Gums: "Is pus coming from your gums?",
  Rapid_Breathing: "Are you breathing rapidly?",
  Rapid_Pulse: "Is your pulse rapid?",
  Rash: "Do you have a rash?",
  Rashes: "Do you have multiple rashes?",
  Red_Eyes: "Are your eyes red?",
  Seizures: "Have you had any seizures?",
  Sensitivity_to_Light: "Are you sensitive to light?",
  Shortness_of_Breath: "Are you experiencing shortness of breath?",
  Sleep_Issues: "Are you having any sleep issues?",
  Slurred_Speech: "Is your speech slurred?",
  Small_Boils_On_the_Skin: "Do you have small boils on your skin?",
  Small_Nail_Pits: "Have you noticed small pits in your nails?",
  Soft_Tongue: "Does your tongue feel unusually soft?",
  Sore: "Do you have a sore anywhere on your body?",
  Sore_Throat: "Do you have a sore throat?",
  Sore_Tongue: "Is your tongue sore?",
  Speech_Difficulty: "Are you having difficulty speaking?",
  Sticky_Eyelids: "Do your eyelids feel sticky?",
  Stiff_Neck: "Do you have a stiff neck?",
  Strong_hands_and_feet:
    "Do your hands and feet feel unusually strong or rigid?",
  Sudden_Uncontrolled_Electrical_Disturbances_in_the_brain:
    "Have you had sudden, uncontrolled electrical disturbances in your brain?",
  Sweating: "Are you sweating excessively?",
  Swelling_of_the_Joints: "Are your joints swollen?",
  Swollen: "Do you have any swelling on your body?",
  Swollen_Ankles: "Are your ankles swollen?",
  Swollen_Eyelids: "Are your eyelids swollen?",
  Swollen_Tongue: "Is your tongue swollen?",
  Talking_Nonsense:
    "Have you been talking nonsense or saying things that don't make sense?",
  Temporary_Distraction:
    "Do you experience moments of temporary distraction or zoning out?",
  Throbbing_around_the_lips: "Do you feel throbbing around your lips?",
  Tingling_in_hands_and_feet:
    "Are you experiencing tingling in your hands and feet?",
  Tongue_Ulcer: "Do you have an ulcer on your tongue?",
  Tooth_Brittle: "Are your teeth brittle?",
  Tremors_in_hands_and_feet:
    "Are you experiencing tremors in your hands and feet?",
  Vaginal_Discharge: "Have you noticed any vaginal discharge?",
  Vomiting: "Are you vomiting?",
  Vomiting_Blood: "Are you vomiting blood?",
  Watery_Eyes: "Do you have watery eyes?",
  Weak_Joints: "Do your joints feel weak?",
  Weakness: "Are you feeling generally weak?",
  Weight_Gain: "Have you noticed unexplained weight gain?",
  Weight_Loss: "Have you noticed unexplained weight loss?",
  White_Spots_on_Mouth: "Have you noticed white spots in your mouth?",
  Yellow_Eyes: "Have your eyes turned yellow?",
  Yellow_Skin: "Has your skin turned yellow?",
  Brain_Confusion:
    "Are you experiencing confusion or trouble thinking clearly?",
  Pain_During_Urination: "Do you feel pain during urination?",
};

export function getQuestion(symptom: string): string {
  return (
    SYMPTOM_QUESTIONS[symptom] ??
    `Are you experiencing ${symptom.replace(/_/g, " ").toLowerCase()}?`
  );
}
